# Eureka Server Configuration
server.port=8761

# Do not register the server itself as a client
eureka.client.register-with-eureka=false

# Do not fetch registry from itself
eureka.client.fetch-registry=false

# Application name
spring.application.name=eureka-server

# Eureka dashboard
eureka.server.enable-self-preservation=false
